package kr.or.ddit.caa.domain;

import lombok.Data;

@Data
public class SalesByIndustryVO {
	
	private String sales_year;
	private String sales_bungi_code;
	private String sales_gb;
	private String sales_gb_name;
	private String sales_bd;
	private String sales_bd_name;
	private String sales_ser;
	private String sales_ser_name;
	private String sales_mnt_price;
	private String sales_mnt_count;
	private String sales_wd_rati;
	private String sales_wk_rati;
	private String sales_mon_rati;
	private String sales_tue_rati;
	private String sales_wed_rati;
	private String sales_thu_rati;
	private String sales_fri_rati;
	private String sales_sat_rati;
	private String sales_sun_rati;
	private String sales_0006_rati;
	private String sales_0611_rati;
	private String sales_1114_rati;
	private String sales_1417_rati;
	private String sales_1721_rati;
	private String sales_2124_rati;
	private String sales_men_rati;
	private String sales_wom_rati;
	private String sales_age_10_rati;
	private String sales_age_20_rati;
	private String sales_age_30_rati;
	private String sales_age_40_rati;
	private String sales_age_50_rati;
	private String sales_age_60_rati;
	private String sales_wd_price;
	private String sales_wk_price;
	private String sales_mon_price;
	private String sales_tue_price;
	private String sales_wed_price;
	private String sales_thu_price;
	private String sales_fri_price;
	private String sales_sat_price;
	private String sales_sun_price;
	private String sales_0006_price;
	private String sales_0611_price;
	private String sales_1114_price;
	private String sales_1417_price;
	private String sales_1721_price;
	private String sales_2124_price;
	private String sales_men_price;
	private String sales_wom_price;
	private String sales_age_10_price;
	private String sales_age_20_price;
	private String sales_age_30_price;
    private String sales_age_40_price   ;
    private String sales_age_50_price  ;
    private String sales_age_60_price  ;
    private String sales_wd_count      ;
    private String sales_wk_count      ;
    private String sales_mon_count     ;
    private String sales_tue_count     ;
    private String sales_wed_count     ;
    private String sales_thu_count     ;
    private String sales_fri_count     ;
    private String sales_sat_count     ;
    private String sales_sun_count     ;
    private String sales_0006_count    ;
    private String sales_0611_count    ;
    private String sales_1114_count    ;
    private String sales_1417_count    ;
    private String sales_1721_count    ;
    private String sales_2124_count    ;
    private String sales_men_count     ;
    private String sales_wom_count     ;
    private String sales_age_10_count  ;
    private String sales_age_20_count  ;
    private String sales_age_30_count  ;
    private String sales_age_40_count  ;
    private String sales_age_50_count  ;
    private String sales_age_60_count  ;
    private String sales_store_count   ;
}